require_relative 'debugging/camera'
require_relative 'debugging/color'
require_relative 'debugging/colored_vertex'
require_relative 'debugging/debug_command'
require_relative 'debugging/debug_data'
require_relative 'debugging/debug_state'